INSERT into Especie(cientifico, popular, familia) values

('Aspidosperma pyrifolium Mart.','pereiro#pau- do- coaru#pequiá- da- mata#pereiro#pau- do- coaru#pequiá- da- mata#pereiro#pau- do- coaru#pequiá- da- mata','Apocynaceae'),
('Attalea maripa (Aubl.) Mart.','inajá#anajá#anajá#anajás#anajax#anajaz#butua-do-corvo#butua-do-curvo#coqueiro-anauyá#coqueiro-enayá#inajá#inajaí#inajazeiro#inayá#najá-coqueiro#nayá (Mato Grosso). Mapia (Waimiri-Atroari)#okolaxi (Xiriana Teri)#rikre (Kayapó).#inajá#anajá','Palmae'),
('Bowdichia virgilioides H.B.K.','sucupira- preta#sucupira- preta#sucupira- preta','Papilionoideae'),
('Caesalpinea ferrea Mart. ex Tul. var. leiostachya Benth.','Pau- ferro#Pau- ferro# Giúna#no Espírito Santo#ibirá-obi#imirá-obi#imirá-itá#jucá e pau-ferro-da-mata#em Pernambuco#muirá-itá#muirá-obi#muirapixuma#mururé#pau-ferro-do-norte#no Rio Grande do Sul#pau-ferro-verdadeiro#na Bahia#peroba-sobro#no Espírito Santo#quebra-foice#no Rio de Janeiro#quiriripiranga.','Fabaceae '),
('Caesalpinia pyramidalis TUL.','Catingueira#Catingueira','Caesalpinaceae'),
('Cassia grandis L.','cássia grande#acácia#marimari#canafístula#cássia-grande#cana-fístula#fedegoso#marizeiro#mata-pasto#cássia-rosa#cássia.','Mimosoideae'),
('Ceiba pentandra (L.) Gaertn.','sumaúma#sumaúma#sumaúma#sumaúma','Bombacaceae'),
('Citharexylum montevidense (Spreng.) Moldenke','tarumã- de- espinho#tarumã- de- espinho','Verbenaceae'),
('Cybistax antisyphilitica Mart.','pé- de- anta#pé- de- anta#ipê-verde','Bignoniaceae'),
('Dalbergia nigra (Vell.) Fr.All. ex Benth.','Jacarandá- da- Bahia#Jacarandá- da- Bahia#Jacarandá- da- Bahia','Fabaceae'),
('Eugenia involucrata DC.','cerejeira#cerejeira- do- mato#cerejeira- da- terra ou cerejeira- do- rio- grande#cerejeira#cerejeira- do- mato#cerejeira- da- terra ou cerejeira- do- rio- grande#cerejeira#cerejeira- do- mato#cerejeira- da- terra ou cerejeira- do- rio- grande','Myrtaceae'),
('Eugenia pyriformis Camb.','uvaia#uvaieira#uvalha#uvalheira#uvaia#uvaieira#uvalha#uvalheira#Jaboticaba-do-campo#uvaia.#eucalipto-do-campo#uvaia#uvalha-do-campo.','Myrtaceae'),
('Genipa americana L.','jenipapeiro#jenipapeiro#jenipapeiro#jenipapeiro#jenipapo#jenipá#jenipaba','Rubiacea'),
('Hymenaea stigonocarpa (Hayne) Mart.','jatobá- do- cerrado#jatobá-do-cerrado#jutaí#jatobá-capo#jatobá-de-cascafina#jitaí ou jutaicica#jatobá-do-cerrado#jutaí#jatobá-capo#jatobá-de-cascafina#jitaí ou jutaicica',''),
('Inga uruguensis Hook. et Arn.','Ingá#ingá#ingá-banana#ingá-do-brejo e ingá-de-quatro-quinas.#ingá#ingá-ferradura#ingá-graúdo#ingá-banana#ingá-de-beira-de-rio#ingá-do-brejo#angá#ingá-de-quatro-quinas e ingazeiro#ingá-mulambo.#ingá#angá#ingá-do-brejo#ingá-banana#ingá-de-quatro-quinas#ingazeiro.#Ingazeira#ingá e angá.#Ingazeira#ingá e angá.','Mimosaceae'),
('Lophantera lactescens Ducke','lofantera-da-amazônia#chuva- de- ouro','Malpighiaceae'),
('Luehea grandiflora Mart. & Zucc.','açoita-cavalo-graúdo#açoita-cavalo-graúdo','Tiliaceae'),
('Machaerium stipitatum (DC.) Vog.','sapuva#sapuva#sapuva#supuvinha','Fabaceae'),
('Maytenus ilicifolia Mart.ex Reiss','espinheira- santa#espinheira- santa','Celastraceae'),
('Oenocarpus bacaba Mart.','Bacaba#bacaba#bacaba-açu#bacaba-verdadeira#ungurahui#manoco#milpesos#punam.#bacaba#bacaba-açu#bacaba-verdadeira#ungurahui#manoco#milpesos#punam.#Bacaba','Arecaceae'),
('Parkia multijuga Benth.','pinho- cuiabano#paricá-de-terra-firme#bajão#faveira-arara-tucupi e pinho-cuiabano.','Fabaceae'),
('Peltophorum dubium (Spreng) Taub.','canafístula#canafístula#Acácia–amarela#amendoim#amendoim– falso#angico–bravo#camurça#curucaia#ibirá#monjoleiro#amendoim–bravo#angico#angico–amarelo#angico–cangalha#angico–vermelho#pororoca#barbatimão#cabeça–de–negro#cabelo–de–negro#cambuí#canafiste#canafrista–branca#canafrístula#cancença#favinha#canela–de–veado#caobi#cássia–amarela#faveira# faveiro#guarucaia#guazu#ibira–puitá#jacarandá–de–flor–amarela#madeira–nova#pau–vermelho#quebra–serra#sobrasil#tamboril#tamboril–branco#tamboril–bravO.','Fabaceae'),
('Platonia insignis Mart.','Bacuri#Bacuri#Bacuri','Clusiaceae'),
('Pterodon pubescens Benth.','sucupira- branca#sucupira- branca#quina-genciana#amendoim-falso#chapadinha#sucupira-branca.','Fabaceae'),
('Qualea grandiflora Mart.','pau-terra#pau-terra-do-campo#pau-terra-do-cerrado#pau-terra#pau-terra-do-campo#pau-terra-do-cerrado#pau-terra#pau-terra-do-campo#pau-terra-do-cerrado','Vochysiaceae'),
('Samanea saman Merril','samãn','Caesalpinoideae'),
('Sapindus saponaria','saboneteira#saboeiro#sabão- de- macaco#sabonete#fruta de sabão#saboneteira#saboeiro#sabão- de- macaco#sabonete#fruta de sabão','Sapindaceae'),
('Stryphnodendron adstringens (Mart.) Cov.','barbatimão#barbatimão',''),
('Stryphonodendron pulcherrimum (Willd.) Hochr ','faveira camuzê','Leguminosae'),
('Tabebuia caraiba (Mart.)Bur.','craibeira#caraiba#paratudo- do- campo#carobeira#craiba#craibeira#caraiba#paratudo- do- campo#carobeira#craiba#craibeira#caraiba#paratudo- do- campo#carobeira#craiba','Bignoniaceae'),
('Tephrosia candida DC.','tefrósia','Papilionoideae'),
('Terminalia argentea','Capitão do mato#capitão#Capitão#capitão-do-cerrado#Capitão-da-mata#capitão#capitão-do-campo.','Combretaceae'),
('Zanthoxylum rhoifolium Lam.','Mamica- de- porca#tembetaria#mamiqueira#mamica- de- cadela#juva#juvevê#teta- de- cadela#espinho- de- vimtém#tembetaru#tambatarão#tinguaciba#guarita#tamanqueira#Mamica- de- porca#tembetaria#mamiqueira#mamica- de- cadela#juva#juvevê#teta- de- cadela#espinho- de- vimtém#tembetaru#tambatarão#tinguaciba#guarita#tamanqueira#Mamica- de- porca#tembetaria#mamiqueira#mamica- de- cadela#juva#juvevê#teta- de- cadela#espinho- de- vimtém#tembetaru#tambatarão#tinguaciba#guarita#tamanqueira#Mamica-de-porca#Limãozinho#tamanqueira#carne-de-anta','Rutaceae'),
('Zizyphus joazeiro MART.','Juazeiro#Juazeiro','Rhamnanaceae');